name: Nox

on:
  pull_request:
  push:
    branches:
      - main


jobs:
  get_matrix:
    runs-on: ubuntu-latest
    name: Get Matrix
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Matrix
        uses: nint8835/nox-build-matrix@v1.0.0
        id: matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
  run_nox:
    runs-on: ubuntu-latest
    needs: get_matrix
    name: Run Nox
    strategy:
      matrix:
        session: ${{ fromJson(needs.get_matrix.outputs.matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nox
        uses: excitedleigh/setup-nox@v2.1.0
      - name: Run session
        run: nox -s "${{ matrix.session }}"